name: 22:00-cron
on:
  schedule:
    - cron: '0 19 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://ohmymood.vercel.app/api/cron'
